default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: spidr_development
  username: aj
  password: code

test:
  <<: *default
  database: spidr_test

production:
  <<: *default
  database: spidr_production
  username: spidr
  password: <%= ENV['SPIDR_DATABASE_PASSWORD'] %>
